/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Paciente;
import model.PlanoA;
import model.PlanoB;

/**
 *
 * @author claudio.silva
 */
public class FormPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPaciente
     */
    public FormPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoPlano = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        rbPA = new javax.swing.JRadioButton();
        rbPB = new javax.swing.JRadioButton();
        lblPA = new javax.swing.JLabel();
        txtPA = new javax.swing.JFormattedTextField();
        lblPB = new javax.swing.JLabel();
        txtPB = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulário de Pacientes");
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setText("Nome:");

        jLabel2.setText("Telefone:");

        buttonGroupTipoPlano.add(rbPA);
        rbPA.setText("Plano Tipo A");
        rbPA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPAItemStateChanged(evt);
            }
        });

        buttonGroupTipoPlano.add(rbPB);
        rbPB.setText("Plano Tipo B");
        rbPB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPBItemStateChanged(evt);
            }
        });
        rbPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPBActionPerformed(evt);
            }
        });

        lblPA.setText("Num. Plano A:");
        lblPA.setEnabled(false);

        try {
            txtPA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.####.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPA.setEnabled(false);

        lblPB.setText("Num. Plano B:");
        lblPB.setEnabled(false);

        try {
            txtPB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.####.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPB.setEnabled(false);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbPA)
                                .addGap(18, 18, 18)
                                .addComponent(rbPB)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPA)
                    .addComponent(rbPB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPA)
                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPB)
                    .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnSalvar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPAItemStateChanged
   verificarPlano();
    }//GEN-LAST:event_rbPAItemStateChanged

    private void rbPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPBActionPerformed
 
    }//GEN-LAST:event_rbPBActionPerformed

    private void rbPBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPBItemStateChanged
    verificarPlano();   
    }//GEN-LAST:event_rbPBItemStateChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    String nome = txtNome.getText();
    String fone = txtTelefone.getText();
    if(rbPA.isSelected()){
        PlanoA pacientePA = new PlanoA();
        pacientePA.nome = nome;
        pacientePA.telefone = fone;
        pacientePA.numeroPA = txtPA.getText();
    }else if(rbPB.isSelected()){
        PlanoB pacientePB = new PlanoB();
        pacientePB.nome = nome;
        pacientePB.telefone = fone;
        pacientePB.numeroPB = txtPB.getText();
    }else{
        Paciente paciente = new Paciente();
        paciente.nome = nome;
        paciente.telefone = fone;
    }
    }//GEN-LAST:event_btnSalvarActionPerformed
private void verificarPlano(){
    if(rbPA.isSelected()){
        
        lblPA.setEnabled(true);
        txtPA.setEnabled(true);
        lblPA.setVisible(true);
        txtPA.setVisible(true);
        
        lblPB.setEnabled(false);
        txtPB.setEnabled(false);
        lblPB.setVisible(false);
        txtPB.setVisible(false);
        
    }else if(rbPB.isSelected()){
        
        lblPA.setEnabled(false);
        txtPA.setEnabled(false);
        lblPA.setVisible(false);
        txtPA.setVisible(false);
        
        lblPB.setEnabled(true);
        txtPB.setEnabled(true);
        lblPB.setVisible(true);
        txtPB.setVisible(true);
    }else{
        lblPB.setEnabled(false);
        txtPB.setEnabled(false);
        lblPB.setVisible(false);
        txtPB.setVisible(false);
        
        lblPA.setEnabled(false);
        txtPA.setEnabled(false);
        lblPA.setVisible(false);
        txtPA.setVisible(false);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroupTipoPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPA;
    private javax.swing.JLabel lblPB;
    private javax.swing.JRadioButton rbPA;
    private javax.swing.JRadioButton rbPB;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtPA;
    private javax.swing.JFormattedTextField txtPB;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
